import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//dmm
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="VVCLAlEAq8Y7bnnaMtA00Et6qCYEqghjr4bhEOf5o9M" />
      <body>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
